### ISSUE TITLE
waht  the" xml trajectory data" means?

### ISSUE THREAD

**Issue by fengminqiang** [samlcharreyron/TrajectoryViewer#1]
hello, i am studying pedestrian tracking recently. Could you write a README file to tell how the program works?

**Comment by samlcharreyron** [comment]
Hi Sorry, this was a project I did in my bachelors for tracking pedestrians using the kinect. The code is not really written to be distributed so I can't really write a README. If you want, you can take a look at the paper: 

Charreyron, Samuel, Stewart Jackson, and Luis F. Miranda-Moreno. "Towards a Flexible System for Pedestrian Data Collection Using a Microsoft Kinect Motion Sensing Device." 92nd Annual Meeting of the Transportation Research Board, Washington, DC. 2013.
